# Generated by Django 4.2.7 on 2023-11-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_name', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/categorias')),
            ],
        ),
    ]
