# Generated by Django 4.2.2 on 2023-11-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variedad'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='variedad_selected',
        ),
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='variedad',
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='variedad',
            field=models.ManyToManyField(blank=True, to='store.variedad'),
        ),
    ]
