# Generated by Django 4.2.2 on 2023-11-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variedad'),
        ('carrito', '0002_carritoitem_user_alter_carritoitem_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='variedades',
            field=models.ManyToManyField(blank=True, to='store.variedad'),
        ),
    ]
